name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: LaTeX compilation
      uses: xu-cheng/latex-action@1.2.1
      with:
          root_file: nazari_milad_voorstel.tex
          working_directory: ./voorstel
        
