name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: compile bachelor thesis proposition
      uses: xu-cheng/latex-action@1.2.1
      with:
          root_file: nazari_milad_voorstel.tex
          working_directory: ./voorstel
    - name: compile bachelor thesis
      uses: xu-cheng/latex-action@1.2.1
      with:
          root_file: bachproef-tin.tex
          working_directory: ./bachproef
    - name: analyse bachelor thesis
      id: analysis
      run: |
        sudo apt-get install python3-setuptools
        pip3 install -r requirements.txt
        echo "::set-output name=analysis_result::$(python3 analyse_bachelor_thesis.py)"
      working-directory: ./bachproef
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%d-%m-%Y_%H:%M')"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: v1.15
          release_name: Release
          draft: false
          prerelease: false
    - name: Upload bachelor thesis proposition
      id: upload-release-bachelor-thesis-proposition 
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./voorstel/nazari_milad_voorstel.pdf
        asset_name: Nazari_Milad_bachelorproef_voorstel.pdf
        asset_content_type: application/pdf
    - name: Upload bachelor thesis
      id: upload-release-bachelor-thesis
      uses: actions/upload-release-asset@v1.0.1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bachproef/bachproef-tin.pdf
        asset_name: Nazari_Milad_2019_bachelorproef.pdf
        asset_content_type: application/pdf
